<<<<<<< HEAD
[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy>=1.19"
]
=======
[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy>=1.19"
]
>>>>>>> 5881ee9d9a49cdc272890e0007b9baca97e186f3
build-backend = "setuptools.build_meta"